import { defineConfig } from 'vitepress'

const base = process.env.VITEPRESS_BASE || '/BMapViewer/'

export default defineConfig({
  base,
  title: 'BMapViewer',
  description: '面向 Vue 3 应用的 Cesium 地理信息可视化 SDK',
  lang: 'zh-CN',
  cleanUrls: true,
  vite: {
    server: {
      port: 1234,
      host: '0.0.0.0',
      strictPort: true,
    },
  },
  themeConfig: {
    nav: [
      { text: '快速开始', link: '/getting-started' },
      { text: '组件 API', link: '/api' },
      { text: '底图', link: '/base-maps' },
      { text: '图层', link: '/layers' },
      { text: '天气粒子', link: '/weather' },
      { text: '在线预览', link: 'https://banyan666.github.io/BMapViewer/' },
      { text: 'GitHub', link: 'https://github.com/banyan666/BMapViewer' },
    ],
    sidebar: [
      {
        text: 'SDK 接入',
        items: [
          { text: '项目介绍', link: '/introduction/index' },
          { text: '快速开始', link: '/getting-started' },
          { text: 'Hello World', link: '/introduction/hello' },
          { text: '组件 API', link: '/api' },
          { text: '底图模块', link: '/base-maps' },
          { text: '图层总览', link: '/layers' },
          { text: '开发与构建', link: '/development' },
        ],
      },
      {
        text: '核心能力',
        items: [
          { text: '数据规范 Data', link: '/data' },
          { text: '综合应用', link: '/examples' },
          { text: 'BMapViewer 组件', link: '/component/index' },
          { text: 'useCesium', link: '/component/use-cesium' },
        ],
      },
      {
        text: '底图 BaseMaps',
        collapsed: false,
        items: [
          { text: '底图模块总览', link: '/base-maps' },
          { text: '离线瓦片', link: '/base-maps/offline' },
          { text: '自定义 Provider', link: '/base-maps/custom-provider' },
          { text: '高德地图', link: '/base-maps/amap' },
          { text: '百度地图', link: '/base-maps/baidu' },
          { text: '腾讯地图', link: '/base-maps/tencent' },
          { text: 'ArcGIS 全球影像', link: '/base-maps/arcgis' },
          { text: 'Google 地图', link: '/base-maps/google' },
          { text: '天地图', link: '/base-maps/tdt' },
          { text: '天地图三维地形', link: '/base-maps/tdt-terrain' },
          { text: 'Cesium World Terrain', link: '/base-maps/cesium-terrain' },
          { text: '星图地球 GeoVis', link: '/base-maps/geovis' },
          { text: '多源 Provider', link: '/base-maps/providers' },
          { text: '坐标系与自定义切片', link: '/base-maps/tiling-schemes' },
        ],
      },
      {
        text: '可视化图层 MapLayers',
        collapsed: false,
        items: [
          { text: 'IconGroupLayer 图标', link: '/layers/icon-group' },
          { text: 'IconClusterLayer 图标聚合', link: '/layers/icon-cluster' },
          { text: 'LabelGroupLayer 文字', link: '/layers/label-group' },
          { text: 'TextGroupLayer Canvas 文字', link: '/layers/text-group' },
          { text: 'BubbleGroupLayer 气泡', link: '/layers/bubble-group' },
          { text: 'BubbleLayer DOM 广告牌', link: '/layers/bubble-dom' },
          { text: 'CircleExplosionLayer 圆爆炸', link: '/layers/circle-explosion' },
          { text: 'CircleWaveLayer 水波纹', link: '/layers/circle-wave' },
          { text: 'PointRippleLayer 点扩散', link: '/layers/point-ripple' },
          { text: 'LineGroupLayer 线', link: '/layers/line-group' },
          { text: 'LinePrimitiveLayer 高性能线', link: '/layers/line-primitive' },
          { text: 'LineMaterialLayer 材质线', link: '/layers/line-material' },
          { text: 'PolygonPrimitiveLayer 面', link: '/layers/polygon-primitive' },
          { text: 'CircleGroupLayer 范围圆', link: '/layers/circle-group' },
          { text: 'MaskLayer 区域遮罩', link: '/layers/mask' },
          { text: 'Build3DLayer 三维白膜', link: '/layers/build-3d' },
          { text: 'GradientWallLayer 渐变立体墙', link: '/layers/gradient-wall' },
          { text: 'DynamicWaterLayer 动态体积水', link: '/layers/dynamic-water' },
          { text: 'HeatmapLayer 热力图', link: '/layers/heatmap' },
          { text: 'HeatmapPrimitiveLayer Primitive 热力图', link: '/layers/heatmap-primitive' },
          { text: 'Heatmap3DLayer 3D 热力图', link: '/layers/heatmap-3d' },
          { text: 'RadarScanner3DLayer 三维雷达', link: '/layers/radar-scanner-3d' },
        ],
      },
      {
        text: '工具',
        items: [
          { text: 'PickTools 拾取总览', link: '/tools/pick-tool' },
          { text: 'pickPoint 点拾取', link: '/tools/pick-point' },
          { text: 'pickPointIcon 图标点', link: '/tools/pick-icon' },
          { text: 'pickLine 线绘制', link: '/tools/pick-line' },
          { text: 'pickPolygon 多边形', link: '/tools/pick-polygon' },
          { text: 'pickSquare 正方形', link: '/tools/pick-square' },
          { text: 'pickRectangle 矩形', link: '/tools/pick-rectangle' },
          { text: 'pickCircle 圆形', link: '/tools/pick-circle' },
          { text: 'pickEllipse 椭圆', link: '/tools/pick-ellipse' },
          { text: 'Turf 空间分析', link: '/tools/turf' },
        ],
      },
      {
        text: '天气 WeatherEffects',
        collapsed: false,
        items: [
          { text: '天气系统总览', link: '/weather' },
          { text: 'RainEffect 降雨', link: '/weather/rain' },
          { text: 'SnowEffect 降雪', link: '/weather/snow' },
          { text: 'FogEffect 距离雾', link: '/weather/fog' },
          { text: 'SandstormEffect 沙尘', link: '/weather/sandstorm' },
          { text: 'CloudEffect 体积云', link: '/weather/cloud' },
          { text: 'RainEffect 雷雨闪电', link: '/weather/lightning' },
        ],
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/banyan666/BMapViewer' },
    ],
    search: {
      provider: 'local',
    },
    editLink: {
      pattern: 'https://github.com/banyan666/BMapViewer/edit/main/docs/:path',
      text: '在 GitHub 上编辑此页',
    },
    footer: {
      message: '基于 Apache-2.0 许可发布',
      copyright: 'BMapViewer',
    },
  },
})
